version: "3.9"
services:
  nginx-w:
    image: nginx:1.0
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
    ports:
      - 80:80
    depends_on:
      - weather
    configs:
      - source: nw.conf
        target: /etc/nginx/sites-available/nw.conf

  weather:
    image: weather:1.0
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3

configs:
  nw.conf:
    file: nw.conf
